[2024-02-29 15:28:52,728] 230 django.request - ERROR -Internal Server Error: /cad
Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: hase.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\PycharmProjects\django\myproject\trade\views.py", line 438, in candlestick_chart_view
    return render(request, 'trade/cad.html')
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\DELL\anaconda3\envs\dai5\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: hase.html
[2024-02-29 16:00:17,866] 251 django.utils.autoreload - INFO -C:\Users\DELL\PycharmProjects\django\myproject\trade\views.py changed, reloading.
